# Generated by Django 5.0.6 on 2024-05-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('x', '0003_alter_x_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='x',
            table='x',
        ),
    ]
